name: Mirror and run GitLab CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Mirror + trigger CI
      uses: SvanBoxel/gitlab-mirror-and-ci-action@master
      with:
        args: "https://gitlab.com/<namespace>/<repository>"
      env:
        FOLLOW_TAGS: "false"
        FORCE_PUSH: "true"
        GITLAB_HOSTNAME: "gitlab.com"
        GITLAB_USERNAME: "c0balt6"
        GITLAB_PASSWORD: ${{ secrets.GITLAB_PASSWORD }} 
        GITLAB_PROJECT_ID: "62918100" 
        GITHUB_TOKEN: ${{ secrets.HUB_TOKEN }} 
