name: GitLab Sync

on: [push, create, delete]

jobs:
  sync:
    name: GitLab Mirror Action
    uses: 0xTheProDev/gitlab-mirror@v1
    with:
      # Enable this boolean flag to push Tags alongside.
      follow-tags: false
      # Enable this boolean flag to overwrite Git history.
      force-push: true
      # Provide hostname for self-hosted GitLab instance.
      hostname: gitlab.com
      # Password or Access Token for GitLab User.
      password: ${{ secrets.GITLAB_PASSWORD }}
      project-id: 62918100
      username: c0balt6
