name: GitLab Sync

on: [push, create, delete]

jobs:
  sync:
    name: Synchronise to GitLab
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: action-pack/gitlab-sync@v3
        with:
          username: c0balt6
          url: "https://gitlab.com/sausage2/NetMafia.git"
          token: ${{ secrets.GITLAB_PASSWORD }}
